# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{dircat}
  s.version = "0.1.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Tokiro"]
  s.date = %q{2010-12-17}
  s.description = %q{
      command line utilites to manage catalogs of directory
    }
  s.email = %q{tokiro.oyama@gmail.com}
  s.executables = ["dircat-build", "dircat-diff", "dircat-query"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION.yml",
    "dircat.gemspec",
    "examples/example.rb",
    "lib/dircat.rb",
    "lib/dircat/cat.rb",
    "lib/dircat/cli/dircat_build.rb",
    "lib/dircat/cli/dircat_diff.rb",
    "lib/dircat/cli/dircat_query.rb",
    "lib/dircat/entry.rb",
    "lib/dircat/extension_md5.rb",
    "lib/dircat/extension_numeric.rb",
    "lib/dircat/report.rb"
  ]
  s.homepage = %q{http://github.com/tokiro/dircat}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{command line utilites to manage catalogs of directory}
  s.test_files = [
    "spec/dircat/cat_spec.rb",
    "spec/dircat/cli/dircat_build_spec.rb",
    "spec/dircat/cli/dircat_query_diff_spec.rb",
    "spec/dircat/cli/dircat_query_spec.rb",
    "spec/dircat/md5_spec.rb",
    "spec/dircat/numeric_spec.rb",
    "spec/fixtures/certified_output/dircat1.yaml",
    "spec/fixtures/certified_output/dircat2.yaml",
    "spec/fixtures/dir1/file1.txt",
    "spec/fixtures/dir1/subdir/file3.txt",
    "spec/fixtures/dir2/file1.txt",
    "spec/fixtures/dir2/file2.txt",
    "spec/fixtures/dir2/subdir/file3.txt",
    "spec/fixtures/dir3/file1.txt",
    "spec/fixtures/dir3/subdir/file1.txt",
    "spec/fixtures/tmp/dummy.txt",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

